default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "community_development" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 55432 } %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_TEST_DB") { "community_test" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 55432 } %>

production:
  primary:
    <<: *default
  cache:
    <<: *default
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    migrations_paths: db/cable_migrate
